name: Build Firmware

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build firmware using ESP-IDF
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.5.3
          target: esp32c3
          path: '.'

      - name: Merge and Export Binary
        run: |
          pip install esptool
          python -m esptool --chip esp32c3 merge_bin -o eva02_stopwatch.bin \
            0x0000 build/bootloader/bootloader.bin \
            0x8000 build/partition_table/partition-table.bin \
            0x10000 build/ai-passport.bin

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: eva02-firmware-bin
          path: eva02_stopwatch.bin
